name: widgetbook_workspace
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.11.0
  widgetbook_annotation: ^3.3.0
  flutter_screenutil: ^5.9.3
  flutter_mvvm_base:
    path: ../
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.10.0
  build_runner: ^2.4.15

dependency_overrides:
  freezed_annotation: 2.2.0

flutter:
  uses-material-design: true
