name: Flutter CI

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  analyze-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Generate code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Analyze code
        run: flutter analyze

      - name: Check code formatting
        run: |
          find . -type d -name widgetbook -prune -o -name "*.dart" -print | xargs dart format --set-exit-if-changed
